### ISSUE TITLE
Some uses of type `number` when `integer` seems more apt.

### ISSUE THREAD

**Issue by naturalethic** [cycleplatform/api-spec#69]
For example: 

```yaml
cpu_cores:
    type: number
    description: The number of CPU Cores availiable for builds
```

In rust, at least, `number` is interpreted as a float.

In any case, I believe `number` should eschewed in favor of more explicit float or integer types.
